# PyMogwai
# example graph configurations
configs:
  modern:
    name: modern
    is_default: true
    custom_loader: modern

  crew:
    name: crew
    is_default: true
    custom_loader: crew

  weimar:
    name: weimar
    file_path: weimar.graphml
    node_label_key: id
    edge_label_key: target
    node_name_key: source

  air-routes-latest:
    name: air-routes-latest
    file_path: air-routes-latest.graphml
    node_label_key: labelV
    edge_label_key: labelE
    node_name_key: code

  air-routes-small:
    name: air-routes-small
    file_path: air-routes-small-latest.graphml
    node_label_key: labelV
    edge_label_key: labelE
    node_name_key: code